# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'book.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_book(object):
    def setupUi(self, book):
        book.setObjectName("book")
        book.resize(435, 376)
        font = QtGui.QFont()
        font.setPointSize(16)
        book.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(book)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(book)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line_bookId = QtWidgets.QLineEdit(book)
        self.line_bookId.setObjectName("line_bookId")
        self.horizontalLayout.addWidget(self.line_bookId)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(book)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.line_bookName = QtWidgets.QLineEdit(book)
        self.line_bookName.setObjectName("line_bookName")
        self.horizontalLayout_2.addWidget(self.line_bookName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(book)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.line_author = QtWidgets.QLineEdit(book)
        self.line_author.setObjectName("line_author")
        self.horizontalLayout_3.addWidget(self.line_author)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(book)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.line_bookNum = QtWidgets.QLineEdit(book)
        self.line_bookNum.setObjectName("line_bookNum")
        self.horizontalLayout_4.addWidget(self.line_bookNum)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.btn_comfirm = QtWidgets.QPushButton(book)
        self.btn_comfirm.setObjectName("btn_comfirm")
        self.horizontalLayout_5.addWidget(self.btn_comfirm)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(book)
        QtCore.QMetaObject.connectSlotsByName(book)

    def retranslateUi(self, book):
        _translate = QtCore.QCoreApplication.translate
        book.setWindowTitle(_translate("book", "书本管理"))
        self.label.setText(_translate("book", "编号："))
        self.label_2.setText(_translate("book", "书名："))
        self.label_3.setText(_translate("book", "作者："))
        self.label_4.setText(_translate("book", "库存："))
        self.btn_comfirm.setText(_translate("book", "确定"))
